plugin:
  update-checks: true
  world-list: []
  list-type: disabled  # disabled | whitelist | blacklist
  gamemode-restricted: false
  gamemode-list: [SURVIVAL, ADVENTURE]

teleport-on-join:
  enabled: false

teleport-on-first-join:
  enabled: true

teleport-on-world-change:
  enabled: false
  check-on-join: false

teleport-out-of-void:
  enabled: true
  check-height: -32

fall-damage:
  enabled: false

use-player-head-rotation:
  enabled: true

particles:
  enabled: true
  particle: CRIT
  amount: 20

sounds:
  enabled: true
  sound: ENTITY_EXPERIENCE_ORB_PICKUP
  volume: 1.0
  pitch: 1.0

teleport-delay:
  enabled: false
  seconds: 3
  blindness: true
  cancel-on-move: true