name: Spawn
main: me.rockquiet.spawn.Spawn
version: 2.4.2-fixed
api-version: '1.20'
author: rockquiet
commands:
  spawn:
    description: Teleport to spawn
    usage: /spawn
    permission: spawn.use
permissions:
  spawn.use:
    default: true
  spawn.bypass.join-teleport:
    default: op
  spawn.bypass.respawn-teleport:
    default: op
  spawn.bypass.world-change-teleport:
    default: op
  spawn.bypass.world-list:
    default: op
  spawn.bypass.void-teleport:
    default: op
  spawn.bypass.cancel-on-move:
    default: op
  spawn.reload:
    default: op